global using static StaticMethods;
global using static Method;
global using static Partials;
global using static CssClasses;
global using Wolverine;
global using Polly;
global using Polly.Fallback;
global using Polly.Retry;
global using Polly.Simmy;
global using Marten;
